up:
    DOCKER_DEFAULT_PLATFORM=linux/amd64 DOCKER_IMAGE_NAME=ghcr.io/pathoplexus/backend:latest docker compose up

down:
    DOCKER_DEFAULT_PLATFORM=linux/amd64 DOCKER_IMAGE_NAME=ghcr.io/pathoplexus/backend:latest docker compose down

db-up:
    DOCKER_DEFAULT_PLATFORM=linux/amd64 DOCKER_IMAGE_NAME=ghcr.io/pathoplexus/backend:latest docker compose up database

db-down:
    DOCKER_DEFAULT_PLATFORM=linux/amd64 DOCKER_IMAGE_NAME=ghcr.io/pathoplexus/backend:latest docker compose down database
