name: loculus-nextclade
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.14.3
  - biopython=1.87
  - dpath=2.2.0
  - nextclade=3.21.0
  - pip=25.2
  - uv=0.11.2
  - PyYAML=6.0.3
  - pyjwt=2.12.1
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - requests=2.33.1
  - pandas=3.0.2
  - ruff=0.15.8
  - types-PyYAML=6.0.12.20250915
  - types-requests=2.33.0.20260327
  - types-python-dateutil=2.9.0.20260124
  - types-pytz=2025.2.0.20251108
  - unidecode=1.4.0
  - pytest=9.0.2
  - pydantic=2.12.5
  - diamond=2.1.24
