@startuml

title ENA Deposition

participant "ENA" as ena #Pink
participant "ENA deposition" as deposition #LightCyan
participant "ENA cronjob" as enacronjob
participant "Slack" as slack
participant "Github" as github
participant "Loculus Backend" as backend #Orange

enacronjob -> backend: Query for all sequences
backend -> enacronjob: All sequences
enacronjob -> slack: All new sequences to deposit in ENA
slack -> github: Manual upload
github -> deposition: Upload of sequences to deposit in ENA
deposition -> ena: Deposition of sequences in ENA
ena -> deposition: Results of deposition (accessions)
deposition -> backend: Upload of deposition results as external metadata

@enduml
