@startuml

title ENA Deposition

participant "ENA" as ena #Pink
participant "ENA deposition" as deposition #LightCyan
participant "ENA cronjob" as enacronjob #LightCyan
participant "Slack Channel" as slack
participant "Github" as github
participant "Loculus Backend" as backend #Orange

enacronjob -> backend: Query for all sequences
activate enacronjob
backend --> enacronjob: All sequences
enacronjob -> slack: All new sequences to deposit in ENA
deactivate enacronjob
slack -> github: Manual upload

deposition -> github: Query for new sequences
activate deposition
github --> deposition: File of sequences to deposit in ENA
deposition -> ena: Submit sequences to ENA
ena --> deposition: Results of deposition (accessions)
deposition -> backend: Upload of deposition results as external metadata
deactivate deposition

@enduml
