@startuml

title Cluster Details
left to right direction

node "Kubernetes Cluster" as loculus {
    portin "Traefik Ingress" as traefik

    component "Loculus Website" as website
    component "Loculus Backend" as backend
    component "Authelia + lldap" as authelia

    node "One instance per organism" {
        component "Processing Pipeline" as processing
        component "LAPIS" as lapis
        component "SILO API" as silo
        component "SILO Preprocessing" as silo_processing
        component "Ingest" as ingest
        component "ENA Deposition" as deposition
    }
}

database "Loculus Database" as db
database "Authelia + lldap Database" as ldap_data

" " --> traefik : HTTP
traefik --> website
traefik --> backend
traefik --> lapis
traefik --> authelia

backend --> db
deposition --> db
authelia --> ldap_data


@enduml
