@startuml

title Deployment Overview

node "Kubernetes Cluster" as loculus {
    collections "Loculus services" as services
}

database "Loculus Database" as db
database "Authelia + lldap Database" as ldap_data

services --> db
services --> ldap_data

@enduml
