name: loculus-ingest
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Core Python dependencies
  - python=3.12.9 # Pinned to 3.12.x series, check for patch updates within 3.12
  # Extra dependencies
  - biopython=1.87
  - click=8.3.3
  - curl=8.20.0
  - ijson=3.5.0
  - jsonlines=4.0.0
  - ncbi-datasets-cli=18.25.1
  - nextclade=3.21.2
  - orjsonl=1.0.0
  - pandas=2.3.3
  - psycopg2=2.9.11
  - pytz=2026.1.post1
  - pyyaml=6.0.3
  - requests=2.33.1
  - seqkit=2.13.0
  - snakefmt=1.1.0
  - snakemake=9.20.0
  - unzip=6.0
  - pytest=9.0.3
