import yaml
from pathlib import Path

with open("config/defaults.yaml") as f:
    defaults = yaml.safe_load(f)

# Merge configs, using defaults only as fallback
# Write to results/config.yaml
merged_config = config
for key, value in defaults.items():
    if not key in config:
        config[key] = value

config = merged_config

Path("results").mkdir(parents=True, exist_ok=True)
with open("results/config.yaml", "w") as f:
    f.write(yaml.dump(merged_config))

TAXON_ID = config["taxon_id"]
ALL_FIELDS = ",".join(config["all_fields"])
COLUMN_MAPPING = config["column_mapping"]
LOG_LEVEL = config.get("log_level", "INFO")


def rename_columns(input_file, output_file):
    with open(input_file, "r") as f:
        header = f.readline().strip().split("\t")
        header = [COLUMN_MAPPING.get(h, h) for h in header]
        with open(output_file, "w") as g:
            g.write("\t".join(header) + "\n")
            for line in f:
                g.write(line)


rule all:
    input:
        "data/sequences.fasta",
        "data/metadata.tsv",


rule fetch_ncbi_dataset_package:
    output:
        dataset_package="results/ncbi_dataset.zip",
    retries: 5
    shell:
        """
        datasets download virus genome taxon {TAXON_ID} \
            --no-progressbar \
            --filename {output.dataset_package}
        """


rule extract_ncbi_dataset_sequences:
    input:
        dataset_package="results/ncbi_dataset.zip",
    output:
        ncbi_dataset_sequences="results/sequences.fasta",
    shell:
        """
        unzip -jp {input.dataset_package} \
            ncbi_dataset/data/genomic.fna \
        | seqkit seq -i -w0 \
        > {output.ncbi_dataset_sequences}
        """


rule calculate_sequence_hashes:
    input:
        sequences="results/sequences.fasta",
    output:
        sequence_hashes="results/sequence_hashes.json",
    shell:
        """
        python scripts/calculate_sequence_hashes.py \
            --input {input.sequences} \
            --output {output.sequence_hashes}
        """


rule format_ncbi_dataset_report:
    input:
        dataset_package="results/ncbi_dataset.zip",
    output:
        ncbi_dataset_tsv="results/metadata_post_extract.tsv",
    params:
        fields_to_include=ALL_FIELDS,
    shell:
        """
        dataformat tsv virus-genome \
            --package {input.dataset_package} \
            --fields {params.fields_to_include:q} \
            > {output.ncbi_dataset_tsv}
        """


rule rename_columns:
    input:
        ncbi_dataset_tsv="results/metadata_post_extract.tsv",
    output:
        ncbi_dataset_tsv="results/metadata_post_rename.tsv",
    run:
        rename_columns(input.ncbi_dataset_tsv, output.ncbi_dataset_tsv)


rule prepare_metadata:
    input:
        metadata="results/metadata_post_rename.tsv",
        sequence_hashes="results/sequence_hashes.tsv",
        config="results/config.yaml",
    output:
        metadata="results/metadata_post_prepare.tsv",
    params:
        log_level=LOG_LEVEL,
    shell:
        """
        python scripts/prepare_metadata.py \
            --config-file {input.config} \
            --input {input.metadata} \
            --sequence-hashes {input.sequence_hashes} \
            --output {output.metadata} \
            --log-level {params.log_level} \
        """


rule download_hashes:
    """Download metadata and sequence hashes of all previously submitted sequences 
    Potentially done via: 
    - curl to /get-released-data
    - jq filtering to ingest user
    - jq subsetting to hashes
    - jq output as tsv

    Only look at the higest loculus version

    Output needs to contain:
    - insdc base accession (no version) 
    - loculus accession
    - metadata hash of highest version
    - sequence hash of highest version
    """
    input:
        config="results/config.yaml",
    output:
        hashes="results/submitted_hashes.json",
    params:
        log_level=LOG_LEVEL,
    shell:
        """
        python scripts/submit_to_loculus.py \
            --mode get-submitted \
            --config-file {input.config} \
            --log-level {params.log_level} \
            --output {output.hashes}
        """


rule compare_hashes:
    input:
        old_hashes="results/submitted_hashes.json",
        metadata="results/metadata_post_prepare.tsv",
    output:
        to_submit="results/to_submit.tsv",
        to_revise="results/to_revise.tsv",
        unchanged="results/unchanged.tsv",
    shell:
        """
        python scripts/compare_hashes.py \
            --old-hashes {input.old_hashes} \
            --sequence-hashes {input.metadata} \
            --metadata {input.metadata} \
            --to-submit {output.to_submit} \
            --to-revise {output.to_revise} \
            --unchanged {output.unchanged} \
        """


rule submit:
    input:
        metadata="results/metadata_post_prepare.tsv",
        sequences="results/sequences.fasta",
        config="results/config.yaml",
        to_submit="results/to_revise.tsv",
    output:
        submitted=touch("results/submitted"),
    params:
        log_level=LOG_LEVEL,
    shell:
        """
        sleep 0
        python scripts/submit_to_loculus.py \
            --mode submit \
            --metadata {input.metadata} \
            --sequences {input.sequences} \
            --config-file {input.config} \
            --to-submit {input.to_submit} \
            --log-level {params.log_level}
        """


rule revise:
    input:
        metadata="results/metadata_post_prepare.tsv",
        sequences="results/sequences.fasta",
        config="results/config.yaml",
        to_revise="results/to_revise.tsv",
    output:
        submitted=touch("results/submitted"),
    params:
        log_level=LOG_LEVEL,
    shell:
        """
        sleep 0
        python scripts/submit_to_loculus.py \
            --mode revise \
            --metadata {input.metadata} \
            --sequences {input.sequences} \
            --config-file {input.config} \
            --to-revise {input.to_revise} \
            --log-level {params.log_level}
        """


rule approve:
    input:
        config="results/config.yaml",
    params:
        log_level=LOG_LEVEL,
    shell:
        """
        python scripts/submit_to_loculus.py \
            --mode approve \
            --config-file {input.config} \
            --log-level {params.log_level} \
        """
