// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 9c2d571d925eab7c50b916ca89472af4955a9151c52acf49f85c062e6deadecf

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "loculus";

export const themeNames: ThemeName[] = ["loculus"];

export type KcEnvName = "PROJECT_NAME" | "REGISTRATION_TERMS_MESSAGE";

export const kcEnvNames: KcEnvName[] = ["PROJECT_NAME", "REGISTRATION_TERMS_MESSAGE"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    PROJECT_NAME: "Loculus",
    REGISTRATION_TERMS_MESSAGE: ""
};

type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
