// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 6fdf6464c2745ee10fbeabd0df9eb834ca1ed7575778dccd8830e4feeeec0a01

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "loculus";

export const themeNames: ThemeName[] = ["loculus"];

export type KcEnvName = "PROJECT_NAME" | "REGISTRATION_TERMS_MESSAGE";

export const kcEnvNames: KcEnvName[] = ["PROJECT_NAME", "REGISTRATION_TERMS_MESSAGE"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    PROJECT_NAME: "Loculus",
    REGISTRATION_TERMS_MESSAGE: ""
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
