// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 54ecacdd0cf16259f1c69b7cb97147df209c9f860534b40638a9c560ed777d5e

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "loculus";

export const themeNames: ThemeName[] = ["loculus"];

export type KcEnvName = "PROJECT_NAME";

export const kcEnvNames: KcEnvName[] = ["PROJECT_NAME"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    PROJECT_NAME: "Loculus"
};

type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
