@startuml

folder SILO-LAPIS {
    component SILO
    component LAPIS
}

component "Loculus Website" as Website
component "Loculus Backend" as Backend
component "Postgres DB" as Postgres
component "Preprocessing Pipeline" as pipeline

component Keycloak

Website --> Keycloak : check authentication
Backend --> Keycloak : check authentication

Website -> Backend : upload sequence data
Backend --> pipeline : fetch new sequence entries
Backend <-> Postgres : persist sequence entries
Backend <-- pipeline : submit enriched sequence entries

SILO <-- Backend : provide sequence entries
LAPIS --> Website : sequence query results
LAPIS <- SILO : sequence query results

@enduml
