@startuml

component "Loculus Website" as Website
component "Ingest Pipeline" as Ingest
component "Loculus Backend" as Backend

component "Postgres DB" as Postgres
component S3

component "Preprocessing Pipeline" as Preprocessing

component Keycloak

frame SILO-LAPIS {
    component SILO
    component LAPIS
}

Website --> Keycloak : authenticate
Backend -right-> Keycloak : authenticate

Website -down-> Backend : upload sequence data
Backend <-down-> Postgres : persist sequence entries
Backend --> Preprocessing : fetch new sequence entries
Backend <-- Preprocessing : submit enriched sequence entries
Ingest -down-> Backend : new Genbank sequences

SILO <-- Backend : provide sequence entries
LAPIS -up-> Website : sequence query results
LAPIS <-down- SILO : sequence query results

Website -> S3: upload extra files
Backend -down-> S3: Set files to public
S3 -down-> Preprocessing: Provide user submitted files

@enduml
