@startuml

component "Loculus Website" as Website

together {
    component "Loculus Backend" as Backend
    component Keycloak
}

component "Postgres DB" as Postgres
component S3

component "Preprocessing Pipeline" as Preprocessing
component "Ingest Pipeline" as Ingest


frame SILO-LAPIS {
    component SILO
    component LAPIS
}

Website --> Keycloak : authenticate
Backend -left-> Keycloak : authenticate

Website -down-> Backend : upload\nsequence data
Backend --> Preprocessing : fetch new\nsequence entries
Backend <-- Preprocessing : submit enriched\nsequence entries
Backend <-down-> Postgres : persist\nsequence entries
Ingest -left-> Backend : new Genbank sequences

Backend -up-> SILO: provide\nsequence entries
LAPIS -left-> Website : sequence query\nresults
LAPIS <-right- SILO : sequence query\nresults

Website -> S3: upload extra files
Backend --> S3: set files to public
S3 --> Preprocessing: provide user submitted files

@enduml
