@startuml
  hide empty description

  state SILO_READY_REVOKED : revoked = true
  state STAGING_REVOKED
  state entry_will_be_deleted

  state is_approved <<choice>>

  [*] --> STAGING_REVOKED : user initiates revocation of an entry in SILO_READY
  STAGING_REVOKED --> is_approved
  is_approved --> SILO_READY_REVOKED : user approves
  is_approved --> entry_will_be_deleted : user rejects
  SILO_READY_REVOKED --> [*]
  entry_will_be_deleted --> [*]
@enduml
