@startuml
    participant "Loculus Frontend / User" as frontend #LightCyan
    participant "Loculus Backend" as backend #Orange
    database "Database" as DB


    frontend -> backend: submit corrected data for existing accessions

    alt accession exists and highest version is 'APPROVED_FOR_RELEASE'
        backend -> DB: insert new version in status 'RECEIVED'
    backend -> frontend: response with accession + new version number
    else
        backend -> frontend: response with error message
    end

    note right of frontend
        At this point the same flow applies as if this was an initial submission
    end note
@enduml
