@startuml
    participant "Pathoplexus Frontend / User" as frontend #LightCyan
    participant "Pathoplexus Backend" as backend #Orange
    database "Database" as DB

    frontend -> backend: wants to revoke already processed sequence\n\
    query sequence that will be revoked

     alt highest version of sequenceID with Status 'SILO_READY' exists
        backend -> DB: insert new version\nwith status 'REVISION_STAGING' \nand ' is_revoked = true'
    backend -> frontend: response with sequenceId + new version number
    else highest version of sequenceID with Status 'SILO_READY' does not exist
        backend -> frontend: response with error message
    end

    alt
        frontend -> backend: confirms revocation
        backend -> DB: set status to 'SILO_READY'
    else
        frontend -> backend: cancels revocation
        backend -> DB: delete latest version \nof the sequence and Status \n'REVOKED_STAGING'
    end
@enduml
