@startuml
    hide empty description

    ' input data
    state INITIAL_DATA as "initial data" #aliceblue;line:blue;line.dotted;text:blue {
        INITIAL_DATA: new unprocessed data
        }
    state REVISION_DATA as "revision data" #aliceblue;line:blue;line.dotted;text:blue {
        REVISION_DATA: already existing sequence
        REVISION_DATA: with status SILO_READY
        REVISION_DATA: + new unprocessed data
    }

    ' status states
    state RECEIVED
    state PROCESSING
    state ERRORED
    state STAGING
    state SILO_READY
    state REVOKED

    ' actions
    state CREATING_SUBMIT as "entry with new sequenceId\n will be created" #lightgreen;line:green;line.dotted
    state CREATING_REVISE as "entry with existing sequenceId\n and incremented version number\n will be created" #lightgreen;line:green;line.dotted
    state DELETION as "entry will be deleted" #IndianRed;line:red;line.dotted
    state is_error_or_not <<choice>>
    state is_approved_or_not <<choice>>

    ' transitions
    INITIAL_DATA -d-> CREATING_SUBMIT : initial submission
    CREATING_SUBMIT -r-> RECEIVED
    REVISION_DATA -d-> CREATING_REVISE : user initiates revision
    CREATING_REVISE -l-> RECEIVED

    RECEIVED --> PROCESSING : preprocessing starts
    PROCESSING -d-> is_error_or_not
    is_error_or_not -l-> ERRORED : data contains error
    is_error_or_not -r-> STAGING : preprocessing successful
    ERRORED -d-> DELETION : deleting data with errors
    STAGING -d-> is_approved_or_not
    is_approved_or_not -d-> SILO_READY : user approves \nor automatic approval\n via 'release_directly'
    is_approved_or_not -l-> DELETION : user rejects

    SILO_READY --> REVOKED : user revokes

@enduml
