organism: "enterovirus"
nextclade_dataset_server: https://clades.nextstrain.org  # overwrites the default value
nucleotideSequences:
  - name: D68
    nextclade_dataset_name: nextclade/d68
    nextclade_dataset_tag: v1.0.0. # can be None
    nextclade_dataset_server: https://clades.nextstrain.org  # has a default value
    accepted_sort_matches: ['d68.1', 'd68']
    gene_prefix: 'D68-' # we need to map the gene names in the nextclade dataset to the gene names in the database
  - name: EV
    nextclade_dataset_name: nextclade/ev-1
    nextclade_dataset_tag: v1.0.0
    nextclade_dataset_server: https://clades.nextstrain.org
    accepted_sort_matches: ['EV1']
    gene_prefix: 'EV-'
genes: ["D68-1", "D68-2", "D68-3", "EV-1", "EV-2", "EV-3"]
classify_with_nextclade_sort: True #default is False
require_nextclade_sort_match: False # default is False
minimizer_url: None
alignment_requirement: "ALL"
backend_host: ""
keycloak_host: "http://127.0.0.1:8083"
keycloak_user: "preprocessing_pipeline"
keycloak_password: "preprocessing_pipeline"  # noqa: S105
keycloak_token_path: "realms/loculus/protocol/openid-connect/token"  # noqa: S105
log_level: "DEBUG"
keep_tmp_dir: False
batch_size: 5
pipeline_version: 1
processing_spec: dict[str, dict[str, Any]] = dataclasses.field(default_factory=dict)
