package org.loculus.backend.config

import org.jetbrains.exposed.v1.core.Table
import org.jetbrains.exposed.v1.jdbc.SchemaUtils
import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider
import org.springframework.core.type.filter.AssignableTypeFilter

/**
 * Marker for Exposed [Table] objects that do NOT map onto a table Flyway is expected to have created, e.g.
 * because they map onto a database VIEW instead (see [org.loculus.backend.service.submission.SequenceEntriesView]).
 * By default we assume every [Table] is Flyway-managed unless it is explicitly marked [NotFlywayManaged].
 */
interface NotFlywayManaged

private const val BASE_PACKAGE = "org.loculus.backend"

private fun discoverFlywayManagedTables(): List<Table> {
    val scanner = ClassPathScanningCandidateComponentProvider(false).apply {
        addIncludeFilter(AssignableTypeFilter(Table::class.java))
    }
    return scanner.findCandidateComponents(BASE_PACKAGE)
        .mapNotNull { Class.forName(it.beanClassName).kotlin.objectInstance as? Table }
        .filterNot { it is NotFlywayManaged }
}

/**
 * Statements needed to bring the database in line with the Exposed table definitions: missing columns, and
 * type/nullability mismatches on existing columns.
 *
 * Foreign-key-constraint statements are filtered out entirely (Exposed's autogenerated FK names differ from
 * Flyway's, not an actual schema problem). Default-value statements are filtered out too, but only when they
 * apply to a column that already exists (an `ALTER COLUMN ...` statement) - matching Exposed's default
 * expressions to the exact SQL text Postgres reports back is too fragile to enforce (e.g. `now()` vs
 * `CURRENT_TIMESTAMP`). A statement that instead *adds* a column that's missing entirely (`ADD <col> <type>
 * ...`, no `ALTER COLUMN`) must never be filtered on the presence of "DEFAULT", even though such a statement
 * routinely contains that word for any missing column that also declares `.default(...)` in Exposed - that
 * would silently hide the exact "column doesn't exist" drift this check exists to catch. Indices, non-FK
 * constraints and sequences are never touched by `addMissingColumnsStatements` in the first place - Flyway,
 * not Exposed, owns those, and this check must never suggest DROPping a structure that Flyway created and
 * Exposed simply doesn't model.
 */
private fun findSchemaDrift(tables: List<Table>): List<String> =
    SchemaUtils.addMissingColumnsStatements(*tables.toTypedArray(), withLogs = false)
        .filterNot { it.contains("CONSTRAINT") && !it.contains("ADD COLUMN") }
        .filterNot { it.contains("ALTER COLUMN") && it.contains("DEFAULT") }

/**
 * Verifies that every Flyway-managed Exposed table (i.e. every [Table] object under `org.loculus.backend`
 * that isn't marked [NotFlywayManaged]) matches the database schema that Flyway just migrated to: same
 * columns, with the same type and nullability. Defaults, indices, non-FK constraints, sequences and
 * foreign-key constraint *names* are allowed to differ between Exposed and the database.
 *
 * Must be called within a transaction, after `flyway.migrate()`.
 */
fun checkExposedSchemaMatchesDatabase() {
    val tables = discoverFlywayManagedTables()
    check(tables.isNotEmpty()) {
        "No Flyway-managed Exposed tables found on the classpath under $BASE_PACKAGE - " +
            "the classpath scan is likely misconfigured."
    }

    val drift = findSchemaDrift(tables)
    check(drift.isEmpty()) {
        "Exposed table definitions are out of sync with the database schema created by Flyway migrations " +
            "(missing columns, or a type/nullability mismatch on an existing column). Update the Exposed " +
            "table definition(s) to match Flyway. Statements required to reconcile:\n" +
            drift.joinToString("\n")
    }
}
