package org.loculus.backend.config

import org.jetbrains.exposed.v1.core.Table
import org.jetbrains.exposed.v1.jdbc.SchemaUtils
import org.jetbrains.exposed.v1.migration.jdbc.MigrationUtils
import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider
import org.springframework.core.type.filter.AssignableTypeFilter

/**
 * Marker for Exposed [Table] objects that do NOT map onto a table Flyway is expected to have created, e.g.
 * because they map onto a database VIEW instead (see [org.loculus.backend.service.submission.SequenceEntriesView]).
 * By default we assume every [Table] is Flyway-managed unless it is explicitly marked [NotFlywayManaged].
 */
interface NotFlywayManaged

private const val BASE_PACKAGE = "org.loculus.backend"

private fun discoverFlywayManagedTables(): List<Table> {
    val scanner = ClassPathScanningCandidateComponentProvider(false).apply {
        addIncludeFilter(AssignableTypeFilter(Table::class.java))
    }
    return scanner.findCandidateComponents(BASE_PACKAGE)
        .mapNotNull { Class.forName(it.beanClassName).kotlin.objectInstance as? Table }
        .filterNot { it is NotFlywayManaged }
}

/**
 * Statements needed to bring the database in line with the Exposed table definitions: columns missing from
 * the database, columns present in the database but missing from Exposed, and type/nullability mismatches
 * on columns that exist on both sides.
 *
 * Constraint statements (e.g. FK, PK) are filtered out entirely (Exposed's autogenerated FK names differ from
 * Flyway's, not an actual schema problem). 
 * Default-value statements are also filtered out (only when a column exists on both sides to prevent new
 * columns with default values from being silently ignored), as validating that the exposed default expressions 
 * map to the exact SQL text Postgres reports back is too fragile to enforce.
 */
private fun findSchemaDrift(tables: List<Table>): List<String> {
    val columnsMissingFromDatabase = SchemaUtils.addMissingColumnsStatements(*tables.toTypedArray(), withLogs = false)
        .filterNot { it.contains("CONSTRAINT") }
        .filterNot { it.contains("ALTER COLUMN") && it.contains("DEFAULT") }
    val columnsMissingFromExposed = MigrationUtils.dropUnmappedColumnsStatements(
        *tables.toTypedArray(),
        withLogs = false,
    )
    return columnsMissingFromDatabase + columnsMissingFromExposed
}

/**
 * Verifies that every Flyway-managed Exposed table (i.e. every [Table] object under `org.loculus.backend`
 * that isn't marked [NotFlywayManaged]) matches the database schema that Flyway just migrated to: same
 * columns on both sides, with the same type and nullability. Defaults, indices, non-FK constraints, sequences
 * and foreign-key constraint *names* are allowed to differ between Exposed and the database.
 *
 * Must be called within a transaction, after `flyway.migrate()`.
 */
fun checkExposedSchemaMatchesDatabase() {
    val tables = discoverFlywayManagedTables()
    check(tables.isNotEmpty()) {
        "No Flyway-managed Exposed tables found on the classpath under $BASE_PACKAGE - " +
            "the classpath scan is likely misconfigured."
    }

    val drift = findSchemaDrift(tables)
    check(drift.isEmpty()) {
        "Exposed table definitions are out of sync with the database schema created by Flyway migrations " +
            "(a column exists on only one side, or has a type/nullability mismatch). Update the Exposed " +
            "table definition(s) or add a Flyway migration to match. Statements required to reconcile:\n" +
            drift.joinToString("\n")
    }
}
