{{/* Common metadata fields are metadata fields that are required for all organisms
for Loculus to work.
In almost all cases (except for versionComment), these fields are not supposed to
be input by the user but are instead generated by the system.
They are defined here so that they can't be misconfigured in values.yaml.
Beware: if a field here is supposed to be user submitted and preprocessed, you need
it's not enough to add the field here, you need to add it in other places.
See https://github.com/loculus-project/loculus/pull/3141 for an example */}}
{{- define "loculus.commonMetadata" }}
fields:
  - name: accessionVersion
    type: string
    notSearchable: true
    hideOnSequenceDetailsPage: true
  - name: accession
    type: string
    notSearchable: true
    hideOnSequenceDetailsPage: true
  - name: version
    type: int
    notSearchable: true
    hideOnSequenceDetailsPage: true
  - name: submissionId
    displayName: Submission ID
    type: string
    header: Submission details
    enableRegex: true
  - name: isRevocation
    type: boolean
    notSearchable: true
    hideOnSequenceDetailsPage: true
  - name: submitter
    type: string
    generateIndex: true
    autocomplete: true
    hideOnSequenceDetailsPage: true
    header: Submission details
  - name: groupName
    type: string
    generateIndex: true
    autocomplete: true
    header: Submission details
    displayName: Submitting group
    customDisplay:
      type: submittingGroup
      displayGroup: group
  - name: groupId
    displayName: Group ID
    type: int
    autocomplete: true
    header: Submission details
    displayName: Submitting group (numeric ID)
    customDisplay:
      type: submittingGroup
      displayGroup: group
  - name: submittedAtTimestamp
    type: timestamp
    displayName: Date submitted
    header: Submission details
  - name: submittedDate
    type: string
    hideOnSequenceDetailsPage: true
    generateIndex: true
    autocomplete: true
    displayName: Date submitted (exact)
  - name: releasedAtTimestamp
    type: timestamp
    displayName: Date released
    header: Submission details
  - name: releasedDate
    type: string
    hideOnSequenceDetailsPage: true
    generateIndex: true
    autocomplete: true
    displayName: Date released (exact)
  - name: dataUseTerms
    type: string
    generateIndex: true
    autocomplete: true
    displayName: Data use terms
    initiallyVisible: true
    customDisplay:
      type: dataUseTerms
    header: Data use terms
  - name: dataUseTermsRestrictedUntil
    type: date
    displayName: Data use terms restricted until
    hideOnSequenceDetailsPage: true
    header: Data use terms
  {{- if $.Values.dataUseTermsUrls }}
  - name: dataUseTermsUrl
    displayName: Data use terms URL
    type: string
    notSearchable: true
    header: Data use terms
    customDisplay:
      type: link
      url: "__value__"
  {{- end}}
  - name: versionStatus
    type: string
    notSearchable: true
    hideOnSequenceDetailsPage: true
  - name: versionComment
    type: string
    displayName: Version comment
    header: Submission details
{{- end}}

{{/* Patches schema by adding to it and overwriting overlapping fields by the value in metadataAdd*/}}
{{- define "loculus.patchMetadataSchema" -}}
{{- $patchedSchema := deepCopy . }}
{{- $metadata := .metadata | default (list) }}
{{- $toAdd := . | dig "metadataAdd" list | default (list) }}
{{- $metadataMap := dict -}}
{{- range $metadata }}
  {{- $key := .name }}
  {{- $metadataMap = merge $metadataMap (dict $key .) -}}
{{- end -}}
{{- range $toAdd }}
  {{- $key := .name }}
  {{- $metadataMap = merge $metadataMap (dict $key .) -}}
{{- end -}}
{{- $patchedMetadata := list -}}
{{- range $key, $value := $metadataMap }}
  {{- $patchedMetadata = append $patchedMetadata $value -}}
{{- end -}}
{{- set $patchedSchema "metadata" $patchedMetadata | toYaml -}}
{{- end -}}

{{/* Generate website config from passed config object */}}
{{- define "loculus.generateWebsiteConfig" }}
name: {{ quote $.Values.name }}
logo: {{ $.Values.logo | toYaml | nindent 6 }}
{{ if $.Values.gitHubMainUrl }}
gitHubMainUrl: {{ quote $.Values.gitHubMainUrl }}
{{ end }}
{{ if $.Values.bannerMessage }}
bannerMessage: {{ quote $.Values.bannerMessage }}
{{ else if or $.Values.runDevelopmentMainDatabase $.Values.runDevelopmentKeycloakDatabase }}
bannerMessage: "Warning: Development or Keycloak main database is enabled. Development environment only."
{{ end }}
{{ if $.Values.gitHubEditLink }}
gitHubEditLink: {{ quote $.Values.gitHubEditLink }}
{{ end }}
{{ if $.Values.additionalHeadHTML }}
additionalHeadHTML: {{ quote $.Values.additionalHeadHTML }}
{{end}}

accessionPrefix: {{ quote $.Values.accessionPrefix }}
{{- $commonMetadata := (include "loculus.commonMetadata" . | fromYaml).fields }}
organisms:
  {{- range $key, $instance := (.Values.organisms | default .Values.defaultOrganisms) }}
  {{ $key }}:
    schema:
      {{- with ($instance.schema | include "loculus.patchMetadataSchema" | fromYaml) }}
      organismName: {{ quote .organismName }}
      loadSequencesAutomatically: {{ .loadSequencesAutomatically | default false }}
      {{- $nucleotideSequences := .nucleotideSequences | default (list "main")}}
      {{ if .image }}
      image: {{ .image }}
      {{ end }}
      {{ if .description }}
      description: {{ quote .description }}
      {{ end }}
      primaryKey: accessionVersion
      inputFields: {{- include "loculus.inputFields" . | nindent 8 }}
        - name: versionComment
          displayName: Version comment
      metadata:
        {{- $args := dict "metadata" (concat $commonMetadata .metadata) "nucleotideSequences" $nucleotideSequences}}
        {{ $metadata := include "loculus.generateWebsiteMetadata" $args | fromYaml }}
        {{ $metadata.fields | toYaml | nindent 8 }}
      {{ .website | toYaml | nindent 6 }}
      {{- end }}
    referenceGenomes:
      {{ $instance.referenceGenomes | toYaml | nindent 6 }}
  {{- end }}
{{- end }}

{{- define "loculus.standardWebsiteMetadata" }}
- type: {{ .type | default "string" | quote }}
  {{- if .autocomplete }}
  autocomplete: {{ .autocomplete }}
  {{- end }}
  {{- if .enableRegex }}
  regexSearch: {{ .enableRegex }}
  {{- end}}
  {{- if .notSearchable }}
  notSearchable: {{ .notSearchable }}
  {{- end }}
  {{- if .initiallyVisible }}
  initiallyVisible: {{ .initiallyVisible }}
  {{- end }}
  {{- if or (or (eq .type "timestamp") (eq .type "date")) .rangeSearch }}
  rangeSearch: true
  {{- end }}
  {{- if .hideOnSequenceDetailsPage }}
  hideOnSequenceDetailsPage: {{ .hideOnSequenceDetailsPage }}
  {{- end }}
  {{- if .truncateColumnDisplayTo }}
  truncateColumnDisplayTo: {{ .truncateColumnDisplayTo }}
  {{- end }}
  {{- if .customDisplay }}
  customDisplay:
    type: {{ quote .customDisplay.type }}
    url: {{ .customDisplay.url }}
    {{- if .customDisplay.displayGroup }}
    displayGroup: {{ quote .customDisplay.displayGroup }}
    {{- end }}
  {{- end }}
{{- end }}

{{/* Generate website metadata from passed metadata array */}}
{{- define "loculus.generateWebsiteMetadata" }}
fields:
{{- $metadataList := .metadata }}
{{/* A segmented organism is defined by having more than 1 segment */}}
{{- $segments := .nucleotideSequences }}
{{- $is_segmented := gt (len $segments) 1 }}
{{- range $metadataList }}
{{- if and $is_segmented .perSegment }}
{{- $currentItem := . }}
{{- range $segment := $segments }}
{{- with $currentItem }}
{{ include "loculus.standardWebsiteMetadata" . }}
  name: {{ printf "%s_%s" .name $segment | quote }}
  {{- if .displayName }}
  displayName: {{ printf "%s %s" .displayName $segment | quote }}
  {{- end }}
  {{- if (default false .oneHeader)}}
  header: {{ (default "Other" .header) | quote }}
  {{- else }}
  header: {{ printf "%s %s" (default "Other" .header) $segment | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- else }}
{{ include "loculus.standardWebsiteMetadata" . }}
  name: {{ quote .name }}
  {{- if .displayName }}
  displayName: {{ quote .displayName }}
  {{- end }}
  header: {{ default "Other" .header }}
{{- end}}
{{- end}}
{{- end}}

{{/* Generate backend config from passed config object */}}
{{- define "loculus.generateBackendConfig" }}
accessionPrefix: {{ quote $.Values.accessionPrefix }}
name: {{ quote $.Values.name }}
dataUseTermsUrls:
  {{$.Values.dataUseTermsUrls | toYaml | nindent 2}}
organisms:
  {{- range $key, $instance := (.Values.organisms | default .Values.defaultOrganisms) }}
  {{ $key }}:
    schema:
      {{- with $instance.schema }}
      {{- $nucleotideSequences := .nucleotideSequences | default (list "main")}}
      organismName: {{ quote .organismName }}
      metadata:
        {{- $args := dict "metadata" (include "loculus.patchMetadataSchema" . | fromYaml).metadata "nucleotideSequences" $nucleotideSequences}}
        {{ $metadata := include "loculus.generateBackendMetadata" $args | fromYaml }}
        {{ $metadata.fields | toYaml | nindent 8 }}
      externalMetadata:
        {{- $args := dict "metadata" (include "loculus.patchMetadataSchema" . | fromYaml).metadata "nucleotideSequences" $nucleotideSequences}}
        {{ $metadata := include "loculus.generateBackendExternalMetadata" $args | fromYaml }}
        {{ $metadata.fields | default list | toYaml | nindent 8 }}
      {{- end }}
    referenceGenomes:
      {{ $referenceGenomes:= include "loculus.generateReferenceGenome" $instance.referenceGenomes | fromYaml }}
      {{ $referenceGenomes | toYaml |nindent 8}}
  {{- end }}
{{- end }}

{{- define "loculus.generateReferenceGenome" }}
nucleotideSequences:
  {{ $nucleotideSequences := include "loculus.generateSequences" .nucleotideSequences | fromYaml }}
  {{ $nucleotideSequences.fields | toYaml | nindent 8 }}
{{ if .genes }}
genes:
  {{ $genes := include "loculus.generateSequences" .genes | fromYaml }}
  {{ $genes.fields | toYaml | nindent 8 }}
{{ else }}
genes: []
{{ end }}
{{- end }}

{{- define "loculus.generateSequences" }}
{{- $sequences := . }}
fields:
  {{- range $sequence := $sequences }}
    - name: {{ printf "%s" $sequence.name | quote}}
      sequence: {{ printf "%s" $sequence.sequence | quote }}
  {{- end }}
{{- end }}

{{/* Generate backend metadata from passed metadata array */}}
{{- define "loculus.generateBackendMetadata" }}
fields:
{{- $metadataList := .metadata }}
{{- $segments := .nucleotideSequences }}
{{- $is_segmented := gt (len $segments) 1 }}
{{- range $metadataList }}
{{- $currentItem := . }}
{{- if and $is_segmented .perSegment }}
{{- range $segment := $segments }}
{{- with $currentItem }}
  - name: {{ printf "%s_%s" .name $segment | quote }}
    type: {{ .type | default "string" | quote }}
{{- end }}
{{- end}}
{{- else }}
  - name: {{ quote .name }}
    type: {{ .type | default "string" | quote }}
{{- end}}
{{- end}}
  - name: versionComment
    type: "string"
{{- end}}

{{/* Generate backend metadata from passed metadata array */}}
{{- define "loculus.generateBackendExternalMetadata" }}
fields:
{{- $metadataList := .metadata }}
{{- $segments := .nucleotideSequences }}
{{- $is_segmented := gt (len $segments) 1 }}
{{- range $metadataList }}
{{- $currentItem := . }}
{{- if eq .header "INSDC" }}
{{- if and $is_segmented .perSegment }}
{{- range $segment := $segments }}
{{- with $currentItem }}
  - name: {{ printf "%s_%s" .name $segment | quote }}
    type: {{ .type | default "string" | quote }}
    {{- if .required }}
    required: {{ .required }}
    {{- end }}
    externalMetadataUpdater: "ena"
{{- end }}
{{- end}}
{{- else }}
  - name: {{ quote .name }}
    type: {{ .type | default "string" | quote }}
    {{- if .required }}
    required: {{ .required }}
    {{- end }}
    externalMetadataUpdater: "ena"
{{- end}}
{{- end}}
{{- end}}
{{- end}}

{{- define "loculus.publicRuntimeConfig" }}
{{- $publicRuntimeConfig := (($.Values.website).runtimeConfig).public }}
{{- $lapisUrlTemplate := "" }}
{{- if $publicRuntimeConfig.lapisUrlTemplate }}
  {{- $lapisUrlTemplate = $publicRuntimeConfig.lapisUrlTemplate }}
{{- else if eq $.Values.environment "server" }}
  {{- $lapisUrlTemplate = printf "https://lapis%s%s/%s" $.Values.subdomainSeparator $.Values.host "%organism%" }}
{{- else }}
  {{- $lapisUrlTemplate = "http://localhost:8080/%organism%" }}
{{- end }}
{{- $externalLapisUrlConfig := dict "lapisUrlTemplate" $lapisUrlTemplate "config" $.Values }}
            {{- if $publicRuntimeConfig.backendUrl }}
            "backendUrl": "{{ $publicRuntimeConfig.backendUrl }}",
            {{- else if eq $.Values.environment "server" }}
            "backendUrl": "https://{{ printf "backend%s%s" $.Values.subdomainSeparator $.Values.host }}",
            {{- else }}
            "backendUrl": "http://localhost:8079",
            {{- end }}
            "lapisUrls": {{- include "loculus.generateExternalLapisUrls" $externalLapisUrlConfig | fromYaml | toJson }},
            "keycloakUrl":  "{{ include "loculus.keycloakUrl" . }}"
{{- end }}


{{/* Generate ENA submission config from passed config object */}}
{{- define "loculus.generateENASubmissionConfig" }}
organisms:
  {{- range $key, $instance := (.Values.organisms | default .Values.defaultOrganisms) }}
  {{- if $instance.ingest }}
  {{ $key }}:
    {{- with $instance.schema }}
    {{- $nucleotideSequences := .nucleotideSequences | default (list "main")}}
    enaDeposition: {{- $instance.enaDeposition.configFile | toYaml | nindent 6 }}
    organismName: {{ quote .organismName }}
    externalMetadata:
      {{- $args := dict "metadata" (include "loculus.patchMetadataSchema" . | fromYaml).metadata "nucleotideSequences" $nucleotideSequences}}
      {{-  $metadata := include "loculus.generateBackendExternalMetadata" $args | fromYaml }}
      {{- $metadata.fields | default list | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
