{{/* Common metadata fields are metadata fields that are required for all organisms
for Loculus to work.
In almost all cases (except for versionComment), these fields are not supposed to
be input by the user but are instead generated by the system.
They are defined here so that they can't be misconfigured in values.yaml.
Beware: if a field here is supposed to be user submitted and preprocessed, you need
it's not enough to add the field here, you need to add it in other places.
See https://github.com/loculus-project/loculus/pull/3141 for an example */}}
{{- define "loculus.commonMetadata" }}
fields:
  - name: accessionVersion
    displayName: Accession version
    type: string
    notSearchable: true
    hideOnSequenceDetailsPage: true
    includeInDownloadsByDefault: true
    definition: {{ printf "The %s `accession` and `version`, uniquely identifying the specific version of the sequence record (e.g. `%s000001.1`)." $.Values.name $.Values.accessionPrefix | quote }}
  - name: accession
    displayName: Accession
    type: string
    notSearchable: true
    hideOnSequenceDetailsPage: true
    definition: {{ printf "A unique identifier assigned to the sequence record by %s (e.g. `%s000001`)." $.Values.name $.Values.accessionPrefix | quote }}
  - name: version
    displayName: Version
    type: int
    hideOnSequenceDetailsPage: true
    definition: "The version number of the sequence record, incremented each time the sequence is revised."
  - name: submissionId
    displayName: Submission ID
    type: string
    header: Submission details
    orderOnDetailsPage: 5000
    enableSubstringSearch: true
    includeInDownloadsByDefault: true
    definition: "The sample identifier provided by the submitter."
  - name: isRevocation
    displayName: Is revocation
    type: boolean
    autocomplete: true
    hideOnSequenceDetailsPage: true
    definition: "Indicator of whether the sequence record is revoked."
  - name: submitter
    displayName: Submitter
    type: string
    generateIndex: true
    autocomplete: true
    hideOnSequenceDetailsPage: true
    header: Submission details
    orderOnDetailsPage: 5010
    definition: {{ printf "Name of the %s user who submitted the sequence record." $.Values.name | quote }}
  - name: groupName
    type: string
    generateIndex: true
    autocomplete: true
    header: Submission details
    displayName: Submitting group
    includeInDownloadsByDefault: true
    orderOnDetailsPage: 5020
    definition: "Name of the group that submitted the sequence record."
    customDisplay:
      type: submittingGroup
      displayGroup: group
  - name: groupId
    type: int
    autocomplete: true
    header: Submission details
    displayName: Submitting group (numeric ID)
    orderOnDetailsPage: 5030
    definition: "Numeric ID of the group that submitted the sequence record."
    customDisplay:
      type: submittingGroup
      displayGroup: group
  - name: submittedAtTimestamp
    type: timestamp
    displayName: Date submitted
    header: Submission details
    orderOnDetailsPage: 5040
    definition: {{ printf "Date and time on which the sequence record was submitted to %s." $.Values.name | quote }}
  - name: submittedDate
    type: string
    hideOnSequenceDetailsPage: true
    generateIndex: true
    autocomplete: true
    displayName: Date submitted (exact)
    orderOnDetailsPage: 5050
    definition: {{ printf "Date on which the sequence record was submitted to %s." $.Values.name | quote }}
  - name: releasedAtTimestamp
    type: timestamp
    displayName: Date released
    header: Submission details
    columnWidth: 100
    orderOnDetailsPage: 5060
    definition: {{ printf "Date and time on which the sequence record was released on %s." $.Values.name | quote }}
  - name: releasedDate
    type: string
    hideOnSequenceDetailsPage: true
    generateIndex: true
    autocomplete: true
    displayName: Date released (exact)
    columnWidth: 100
    orderOnDetailsPage: 5070
    definition: {{ printf "Date on which the sequence record was released on %s." $.Values.name | quote }}
  {{- if $.Values.dataUseTerms.enabled }}
  - name: dataUseTerms
    type: string
    generateIndex: true
    autocomplete: true
    displayName: Data use terms
    initiallyVisible: true
    includeInDownloadsByDefault: true
    definition: "The terms under which the sequence record may be used; either `OPEN` or `RESTRICTED`."
    customDisplay:
      type: dataUseTerms
    header: Data use terms
    orderOnDetailsPage: 610
    orderInSearchDisplay: 10
  - name: dataUseTermsRestrictedUntil
    type: date
    displayName: Data use terms restricted until
    hideOnSequenceDetailsPage: true
    header: Data use terms
    orderOnDetailsPage: 620
    definition: "The date until which the sequence record is restricted use."
  - name: dataBecameOpenAt
    type: date
    displayName: Date data became open
    hideOnSequenceDetailsPage: true
    header: Data use terms
    orderOnDetailsPage: 625
    definition: "The date on which the sequence record transitioned from restricted to open access."
  {{- if $.Values.dataUseTerms.urls }}
  - name: dataUseTermsUrl
    displayName: Data use terms URL
    type: string
    notSearchable: true
    header: Data use terms
    includeInDownloadsByDefault: true
    definition: "Link to the full text of the data use terms applicable to the sequence record."
    customDisplay:
      type: link
      url: "__value__"
    orderOnDetailsPage: 630
  {{- end}}
  {{- end}}
  - name: versionStatus
    displayName: Version status
    type: string
    autocomplete: true
    hideOnSequenceDetailsPage: true
    definition: "Indicates whether this is the latest version of the sequence record (`LATEST_VERSION`), an earlier version (`REVISED`), or has been revoked (`REVOKED`)."
  - name: versionComment
    type: string
    displayName: Version comment
    header: Submission details
    orderOnDetailsPage: 5000
    definition: "Reason for revising sequences, or other general comments concerning a specific version."
  - name: pipelineVersion
    displayName: Pipeline version
    type: int
    notSearchable: true
    hideOnSequenceDetailsPage: true
    definition: "The version of the processing pipeline used to process the sequence record."
{{- end}}

{{/* Patches schema by adding to it and overwriting overlapping fields by the value in metadataAdd*/}}
{{- define "loculus.patchMetadataSchema" -}}
{{- $patchedSchema := deepCopy . }}
{{- $metadata := .metadata | default (list) }}
{{- $toAdd := . | dig "metadataAdd" list | default (list) }}
{{- $metadataMap := dict -}}
{{- range $metadata }}
  {{- $key := .name }}
  {{- $metadataMap = merge $metadataMap (dict $key .) -}}
{{- end -}}
{{- range $toAdd }}
  {{- $key := .name }}
  {{- $metadataMap = set $metadataMap $key . -}}
{{- end -}}
{{- $patchedMetadata := list -}}
{{- range $key, $value := $metadataMap }}
  {{- $patchedMetadata = append $patchedMetadata $value -}}
{{- end -}}
{{- set $patchedSchema "metadata" $patchedMetadata | toYaml -}}
{{- end -}}

{{/* Backend config: technical/operational params only. Domain config
     (organisms, schemas, reference genomes, metadata, dataUseTerms,
     accessionPrefix, fileSharing) lives in the database (config_* tables) and is
     read by the backend via ConfigService — it is NOT sourced from this file.
     The backend binds the fields below from Spring properties, not this file;
     they are emitted here for parity/inspection only. */}}
{{- define "loculus.generateBackendConfig" }}
zstdCompressionLevel: {{ $.Values.zstdCompressionLevel }}
pipelineVersionUpgradeCheckIntervalSeconds: {{ $.Values.pipelineVersionUpgradeCheckIntervalSeconds }}
readOnlyMode: {{ $.Values.readOnlyMode | default false }}
websiteUrl: {{ include "loculus.websiteUrl" . }}
backendUrl: {{ include "loculus.backendUrl" . }}
{{- end }}

{{/* Generate backend metadata from passed metadata array */}}
{{- define "loculus.generateBackendExternalMetadata" }}
{{- $rawUniqueSegments := (include "loculus.getNucleotideSegmentNames" .referenceGenomes | fromYaml).segments }}
{{- $isSegmented := gt (len $rawUniqueSegments) 1 }}
{{- $metadataList := .metadata }}
fields:
{{- range $metadataList }}
{{- $currentItem := . }}
{{- if eq .header "INSDC" }}
{{- if and $isSegmented .perSegment }}
{{- range $segment := $rawUniqueSegments }}
{{- with $currentItem }}
  - name: {{ printf "%s_%s" .name $segment | quote }}
    type: {{ .type | default "string" | quote }}
    {{- if .required }}
    required: {{ .required }}
    {{- end }}
    externalMetadataUpdater: "ena"
{{- end }}
{{- end}}
{{- else }}
  - name: {{ quote .name }}
    type: {{ .type | default "string" | quote }}
    {{- if .required }}
    required: {{ .required }}
    {{- end }}
    externalMetadataUpdater: "ena"
{{- end}}
{{- end}}
{{- end}}
{{- end}}

{{- define "loculus.publicRuntimeConfig" }}
            "backendUrl": "{{ include "loculus.backendUrl" . }}",
            "keycloakUrl":  "{{ include "loculus.keycloakUrl" . }}"
{{- end }}


{{/* Generate ENA submission config from passed config object */}}
{{- define "loculus.generateENASubmissionConfig" }}
enaOrganisms:
  {{- range $_, $item := (include "loculus.enabledOrganisms" . | fromJson).organisms }}
{{- $key := $item.key }}
{{- $instance := $item.contents }}
  {{- if $instance.enaDeposition }}
  {{- range $suborganismName, $configFile := $instance.enaDeposition -}}
  {{- if eq $suborganismName "singleReference" }}
  {{ $key }}:
  {{- else }}
  {{ $suborganismName }}:
    loculusOrganism: {{ quote $key }}
  {{- end }}
  {{- with $instance.schema }}
    {{ $configFile.configFile | toYaml | nindent 4 }}
    {{- if $configFile.referenceIdentifierField }}
    referenceIdentifierField: {{ quote $configFile.referenceIdentifierField }}
    {{- end }}
    organismName: {{ quote .organismName }}
    {{- $rawUniqueSegments := (include "loculus.getNucleotideSegmentNames" $instance.referenceGenomes | fromYaml).segments }}
    segments: {{ $rawUniqueSegments | toYaml | nindent 6 }}
    externalMetadata:
      {{- $args := dict
        "metadata" (include "loculus.patchMetadataSchema" . | fromYaml).metadata
        "referenceGenomes" $instance.referenceGenomes
      }}
      {{-  $metadata := include "loculus.generateBackendExternalMetadata" $args | fromYaml }}
      {{- $metadata.fields | default list | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
