{{- if not .Values.disableIngest }}
{{- $testconfig := .Values.testconfig | default false }}
{{- $backendHost := .Values.environment | eq "server" | ternary (printf "https://backend%s%s" .Values.subdomainSeparator $.Values.host) ($testconfig | ternary (printf "http://%s:8079" $.Values.localHost) "http://loculus-backend-service:8079") }}
{{- $keycloakHost := $testconfig | ternary (printf "http://%s:9091" $.Values.localHost) "http://loculus-authelia-service:9091" }}
{{- $organismKeys := list }}
{{- range $_, $item := (include "loculus.enabledOrganisms" . | fromJson).organisms }}
  {{- if $item.contents.ingest }}
  {{- $organismKeys = append $organismKeys $item.key }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loculus-autoapprove-config
data:
  config.yaml: |
    organisms: {{ $organismKeys | toJson }}
    backend_url: {{ $backendHost }}
    keycloak_token_url: {{ $keycloakHost -}}/api/oidc/token
{{- end }}
