{{- if not .Values.disableIngest }}
{{- $dockerTag := include "loculus.dockerTag" .Values }}
{{- $testconfig := .Values.testconfig | default false }}
{{- $backendHost := .Values.environment | eq "server" | ternary (printf "https://backend%s%s" .Values.subdomainSeparator $.Values.host) ($testconfig | ternary (printf "http://%s:8079" $.Values.localHost) "http://loculus-backend-service:8079") }}
{{- $keycloakHost := $testconfig | ternary (printf "http://%s:8083" $.Values.localHost) "http://loculus-keycloak-service:8083" }}
{{- $organismKeys := list }}
{{- range $_, $item := (include "loculus.enabledOrganisms" . | fromJson).organisms }}
  {{- if $item.contents.ingest }}
  {{- $organismKeys = append $organismKeys $item.key }}
  {{- end }}
{{- end }}
{{- if $organismKeys }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loculus-autoapprove-deployment
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: loculus
      component: loculus-autoapprove-deployment
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        app: loculus
        component: loculus-autoapprove-deployment
    spec:
      {{- include "possiblePriorityClassName" $ | nindent 6 }}
      containers:
        - name: autoapprove
          image: ghcr.io/loculus-project/ingest:{{ $dockerTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- include "loculus.resources" (list "ingest" .Values) | nindent 10 }}
          env:
            - name: KEYCLOAK_INGEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-accounts
                  key: insdcIngestUserPassword
            - name: BACKEND_URL
              value: {{ $backendHost | quote }}
            - name: KEYCLOAK_TOKEN_URL
              value: {{ printf "%s/realms/loculus/protocol/openid-connect/token" $keycloakHost | quote }}
          args:
            - python
            - scripts/autoapprove.py
            {{- range $organismKeys }}
            - --organism
            - {{ . | quote }}
            {{- end }}
{{- end }}
{{- end }}
