{{- if not .Values.disableIngest }}
{{- $testconfig := .Values.testconfig | default false }}
{{- $backendHost := .Values.environment | eq "server" | ternary (printf "https://backend%s%s" .Values.subdomainSeparator $.Values.host) ($testconfig | ternary (printf "http://%s:8079" $.Values.localHost) "http://loculus-backend-service:8079") }}
{{- $keycloakHost := $testconfig | ternary (printf "http://%s:8083" $.Values.localHost) "http://loculus-keycloak-service:8083" }}
{{- $organismKeys := list }}
{{- range $_, $item := (include "loculus.enabledOrganisms" . | fromJson).organisms }}
  {{- if $item.contents.ingest }}
  {{- $organismKeys = append $organismKeys $item.key }}
  {{- end }}
{{- end }}
{{- if $organismKeys }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loculus-autoapprove-config
data:
  config.yaml: |
    organisms:
    {{- range $organismKeys }}
      - {{ . }}
    {{- end }}
    backend_url: {{ $backendHost }}
    keycloak_token_url: {{ $keycloakHost -}}/realms/loculus/protocol/openid-connect/token
    keycloak_client_id: backend-client
    username: insdc_ingest_user
    password: insdc_ingest_user
    time_between_approve_requests_seconds: 60
    backend_request_timeout_seconds: 600
{{- end }}
{{- end }}
