{{- $dockerTag := include "loculus.dockerTag" .Values }}
{{- if not .Values.disableIngest }}
{{- range $i, $item := (include "loculus.enabledOrganisms" . | fromJson).organisms }}
{{- $key := $item.key }}
{{- $organismContent := $item.contents }}
{{- if $organismContent.ingest }}
{{- $schedule := "* * * * *" }}
{{- if $.Values.ingestStaggered }}
{{- $hourOffset := mod $i 12 }}
{{- $schedule = printf "0 %d,%d * * *" $hourOffset (add $hourOffset 12) }}
{{- end }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loculus-ingest-cronjob-{{ $key }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  schedule: {{ $schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $.Values.ingestLimitSeconds }}
      template:
        metadata:
          labels:
            app: loculus
            component: loculus-ingest-cronjob-{{ $key }}
        spec:
          {{- include "possiblePriorityClassName" $ | nindent 10 }}
          restartPolicy: OnFailure
          {{- include "loculus.ingest.podSpecContents" (list $key $dockerTag $organismContent $) | nindent 10 }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loculus-revoke-and-regroup-cronjob-{{ $key }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  schedule: "0 0 31 2 *" # Never runs without manual trigger
  suspend: true
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ $.Values.ingestLimitSeconds }}
      template:
        metadata:
          labels:
            app: loculus
            component: loculus-ingest-cronjob-{{ $key }}
        spec:
          {{- include "possiblePriorityClassName" $ | nindent 10 }}
          restartPolicy: Never
          containers:
            - name: ingest-{{ $key }}
              image: {{ $organismContent.ingest.image}}:{{ $dockerTag }}
              imagePullPolicy: {{ $.Values.imagePullPolicy }}
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "200m"
                limits:
                  cpu: "200m"
                  memory: "10Gi"
              env:
                - name: KEYCLOAK_INGEST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: service-accounts
                      key: insdcIngestUserPassword
              args:
                - snakemake
                - results/submitted
                - results/revised
                - results/revoked
                - results/approved
                - --all-temp # Reduce disk usage by not keeping files around
          {{- if $organismContent.ingest.configFile }}
              volumeMounts:
                - name: loculus-ingest-config-volume-{{ $key }}
                  mountPath: /package/config/config.yaml
                  subPath: config.yaml
          volumes:
            - name: loculus-ingest-config-volume-{{ $key }}
              configMap:
                name: loculus-ingest-config-{{ $key }}
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
