{{- $commonMetadata := (include "loculus.commonMetadata" . | fromYaml).fields }}
{{- $organisms := (include "loculus.enabledOrganisms" . | fromJson).organisms }}
{{- $args := dict
    "commonMetadata" $commonMetadata
    "sharedMetadata" $.Values.sharedMetadata
    "organisms" $organisms
}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lapis-silo-database-config
data:
  database_config.yaml: |
    {{ include "loculus.unifiedSiloDatabaseConfig" $args | nindent 4 }}

  preprocessing_config.yaml: |
    inputDirectory: /preprocessing/input
    outputDirectory: /preprocessing/output
    ndjsonInputFilename: data.ndjson.zst
    referenceGenomeFilename: reference_genomes.json

  reference_genomes.json: |
    {{ include "loculus.mergeAllOrganismReferenceGenomes" (dict "organisms" $organisms) | fromYaml | toJson }}
