---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loculus-website-config
data:
  website_config.json: |
    {{ include "loculus.generateWebsiteConfig" . | fromYaml | toJson }}
  runtime_config.json: |
    {
        "name" : "{{ $.Values.name }}",
        "insecureCookies": {{ $.Values.insecureCookies }},
        "serverSide": {
            {{- if .Values.usePublicRuntimeConfigAsServerSide }}
            {{- template "loculus.publicRuntimeConfig" . -}}
            {{- else }}
            {{ if $.Values.disableBackend -}}
            "backendUrl": "http://{{ $.Values.localHost }}:8079",
            {{- else -}}
            "backendUrl": "http://loculus-backend-service:8079",
            {{- end }}
            "lapisUrls": {{- include "loculus.generateInternalLapisUrls" . | fromYaml | toJson }},
            "autheliaUrl": "{{ if not .Values.disableWebsite -}}{{ include "loculus.autheliaUrlInternal" . }}{{ else -}}http://{{ $.Values.localHost }}:9091{{ end }}",
            "autheliaPublicUrl": "{{ include "loculus.autheliaUrl" . }}",
            "registrationUrl": "{{ include "loculus.registrationUrl" . }}"
            {{- end }}
        },
        "public": {
          {{- template "loculus.publicRuntimeConfig" . -}}
        }
    }
