{{- if and (not .Values.disableBackend) .Values.enableServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loculus-backend
  labels:
    app: loculus
    component: backend
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: loculus
      component: backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
{{- end }}
