name: loculus-ena-submission
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # Core Python dependencies
  - python=3.14.6 # Pinned to 3.12.x series, check for patch updates within 3.12
  - pip=25.2
  - uv=0.11.28
  # Extra dependencies
  - beautifulsoup4=4.15.0
  - click=8.4.2
  - ena-webin-cli=9.0.3
  - fastapi=0.139.0
  - pydantic=2.13.4
  - jsonlines=4.0.0
  - pyyaml=6.0.3
  - requests=2.34.2
  - unzip=6.0
  - psycopg2=2.9.12
  - sqlalchemy=2.0.51
  - slack_sdk=3.43.0
  - xmltodict=1.0.4
  - biopython=1.87
  - pytz=2025.2
  - ruff=0.15.21 # if changing update .pre-commit-config.yaml as well
  - tenacity=9.1.4
  - types-pytz=2025.2.0.20250809
  - types-psycopg2=2.9.21.20251012
  - types-requests=2.33.0.20260518
  - types-pyyaml=6.0.12.20250915
  - types-xmltodict=1.0.1.20250920
  - python-dotenv=1.2.2
  - pytest=8.4.2
  - unidecode=1.4.0
  - orjson
  - orjsonl
  - deepdiff
