rule get_ena_submission_list:
    input:
        script="scripts/get_ena_submission_list.py",
        config="config/config.yaml",
    output:
        released="results/ena_submission_list.json",
    shell:
        """
        python {input.script} \
                --config-file {input.config} \
                --output-file {output.released} \
        """

