log_level: DEBUG
backend_request_timeout_seconds: 600
file_service_host: "0.0.0.0"
deacon_max_host_reads_proportion: 0.4
deacon_max_host_bp: 300000000 # 300kBp - or 10^-4 coverage of the human genome
deacon_a: 2
deacon_r: 0.05
