name: keycloakify-build

on:
  push:

env:
  DOCKER_IMAGE_NAME: ghcr.io/loculus-project/keycloakify

defaults:
  run:
    working-directory: ./keykloak/keycloakify

concurrency:
  group: ci-${{ github.ref }}-keycloak
  cancel-in-progress: true

jobs:
  dockerImage:
    name: Build keycloakify Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: dockerMetadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,prefix=commit-
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./keycloak/keycloakify
          push: true
          tags: ${{ steps.dockerMetadata.outputs.tags }}
          cache-from: type=gha,scope=config-preprocessor=${{ github.ref }}
          cache-to: type=gha,mode=max,scope=config-preprocessor=${{ github.ref }}
